version: "3.3"
services:
  mongo:
    image: 'mongo:4.4.18'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE : 'admin'
    ports:
      - '27017:27017'
    volumes:
      - ${MONGO_DATA_VOLUME_PATH}:/data/db
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: stdallona/plc-testbench-ui:1.0.0
    cpus: 8.0
    mem_reservation: 32gb
    mem_limit: 32gb
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_DEBUG: ${FLASK_DEBUG}
      DATA_FOLDER: /data/original_tracks
      DB_CONN_STRING: ${DB_CONN_STRING}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GEVENT_SUPPORT: ${GEVENT_SUPPORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_OAUTH_CERTS: ${GOOGLE_OAUTH_CERTS}
      REQUESTS_CA_BUNDLE: ${REQUESTS_CA_BUNDLE}
      CERT_FILE: ${CERT_FILE}
      KEY_FILE: ${KEY_FILE}
    ports:
      - '5000:5000'
    volumes:
      - ${FRONTEND_DATA_FOLDER}:/data/original_tracks